### ISSUE TITLE
Benchmarks with memory allocations

### ISSUE THREAD

**Issue by pellared** [yuseferi/zax#14]
I think you should update your benchmark results with the memory allocations.

Zap is not only about being fast but also about having low amount of memory allocations.

**Comment by yuseferi** [comment]
Hey @pellared ,

Thank you for your attention,
as you see in the Readme of the repository the number of allocations is there. ( second column)

```
pkg: github.com/yuseferi/zax/v2
BenchmarkLoggingWithOnlyZap-10          344718321               35.23 ns/op
BenchmarkLoggingWithOnlyZap-10          340526908               36.74 ns/op
BenchmarkLoggingWithOnlyZap-10          337279976               36.17 ns/op
BenchmarkLoggingWithOnlyZap-10          338681052               36.18 ns/op
BenchmarkLoggingWithOnlyZap-10          339414484               35.48 ns/op
BenchmarkLoggingWithZax-10              201602071               56.58 ns/op
BenchmarkLoggingWithZax-10              213688218               57.44 ns/op
BenchmarkLoggingWithZax-10              206059045               56.66 ns/op
BenchmarkLoggingWithZax-10              211847756               58.14 ns/op
BenchmarkLoggingWithZax-10              210184916               56.69 ns/op
```

maybe I need to add column titles to make more sense.

Cheers,

**Comment by pellared** [comment]
The second column is the number of iterations. See https://go.googlesource.com/proposal/+/master/design/14313-benchmark-format.md

**Comment by yuseferi** [comment]
Got your point. I'm a bit busy nowadays but I will add it ;)

**Comment by yuseferi** [comment]
Hey,
I just added  #15  which is adding more details to the benchmark including adding memory allocation + comparing v1,v2, and zap.

Thank you for your attention. and feel free to share more thoughts to make it better.

Cheers,
